### ISSUE TITLE
Inconsistencies between website and Illustrator assets 

### ISSUE THREAD

**Issue by esgoodman** [uswds/uswds-for-designers#11]
### Here's what a password reset form looks like in Components_sticker_sheet_1.0.ai

<img width="247" alt="screen shot 2015-09-23 at 11 17 54 am" src="https://cloud.githubusercontent.com/assets/10067318/10054505/3e0708b0-61e6-11e5-8334-a6d7c6c4ae75.png">
### Here's what the same password reset form looks like on https://pages.18f.gov/designstandards/form-templates/

<img width="1203" alt="screen shot 2015-09-23 at 11 17 33 am" src="https://cloud.githubusercontent.com/assets/10067318/10054602/e65027a4-61e6-11e5-94cf-75e6f197651d.png">

My current plan is to make the Sketch file match @angel's Illustrator file. But that might not be the most recent version...

**Comment by ahelkit** [comment]
@esgoodman the site is correct. I'm going to update the font styles for those two! Thanks for catching that.

**Comment by esgoodman** [comment]
One more question: are there supposed to be check marks next to the list items in the alert box?

**Comment by ahelkit** [comment]
@esgoodman yes, they are there once the user enters their new password. They are validation checkmarks. If you enter text that corresponds to those rules into our live site you should see the checkmarks. Let me know if you have any other questions. Thanks!

**Comment by esgoodman** [comment]
Aha! Question answered.

**Comment by mollieru** [comment]
@esgoodman @angel you gals good here? ok to close this out?

**Comment by ahelkit** [comment]
@mollieru yes, we're good!
