### ISSUE TITLE
First Column of Illustrator file out of alignment

### ISSUE THREAD

**Issue by rtwell** [uswds/uswds-for-designers#16]
@mollieru I noticed that the 1. 2. 3. etc listing below the **Merriweather headings and body** are out of alignment in both the Typography_v.8.ai and the Typography_v.8.eps files. Screen shot attached for your reference. 
![image](https://cloud.githubusercontent.com/assets/12564977/10352370/4bb614ae-6d14-11e5-8c0f-d0f6c47a6de5.png)

**Comment by mollieru** [comment]
Moving this over to an issue here https://github.com/18F/web-design-standards/issues/872 in main repo to be followed up on.

**Comment by carodew** [comment]
This issue was fixed in #20 🎉 !

**Comment by carodew** [comment]
Got excited, these changes should be added to the downloadable zip before this issue is closed. womp womp.

**Comment by carodew** [comment]
Is in fact complete, the ZIP download is of this entire repo. Automation FTW!
