### ISSUE TITLE
Misspelling in Sketch file

### ISSUE THREAD

**Issue by maya** [uswds/uswds-for-designers#18]
via @OpenGlobe in https://github.com/18F/web-design-standards/issues/1110:

> In Components_sticker_sheet_v.8.sketch file, more is mispelled:
> 
> Wherever appropriate, we have created type styles and layer styles to make these components moree easily adapted.
> 
> Would suggest simply changing to:
> 
> "Where appropriate we have created type and layer styles to make the components easier to adapt."

**Comment by carodew** [comment]
I fixed this typo on my local computer (in my local repo) – would you be willing to walk me through how to push the change? Assuming I will need to push to a branch and submit a PR (but that seems a little more complicated than I know how to do in terminal).

**Comment by maya** [comment]
Sure, from terminal it's `git push -u origin my-branch-name` but also you should be able to drag and drop the file directly in the directory on the GitHub interface and when it asks you how you want to commit the changes you can create a new branch. And then you can do whatever other changes needed on that branch.

**Comment by carodew** [comment]
This issue was fixed in #20 🎉

**Comment by carodew** [comment]
Got excited, these changes should be added to the downloadable zip before this issue is closed. womp womp.

**Comment by carodew** [comment]
Is in fact complete, the ZIP download is of this entire repo. Automation FTW!
