### ISSUE TITLE
Create a color palette file for Sketch

### ISSUE THREAD

**Issue by ericadeahl** [uswds/uswds-for-designers#23]
I don't _think_ there's a native way to add a color palette in Sketch, but it would be helpful to provide the color palette as a .clr file for Sketch users a la: https://medium.com/@san_toki/import-the-material-design-color-palette-into-sketch-3-e31caf2f6a12#.xbadr56sz

**Comment by thecristen** [comment]
This might be facilitated by using the Craft series of plugins! 
https://labs.invisionapp.com/craft

**Comment by rtwell** [comment]
if you use the [Sketch Palette plug-in](https://github.com/andrewfiorillo/sketch-palettes) you can use this:
[WDS.sketchpalette.zip](https://github.com/18F/web-design-standards-assets/files/278420/WDS.sketchpalette.zip)
Or we could use a Sketch version of the AI colors, attached!
[WDS_colors.sketch.zip](https://github.com/18F/web-design-standards-assets/files/278423/WDS_colors.sketch.zip)

@ericadeahl ^^

**Comment by ericadeahl** [comment]
Addressed by #29 (we added color swatches into the Sketch sticker sheet) and #31 (we added the Sketch palette file to the colors folder)
