### ISSUE TITLE
A few errors in the v.8 AI file

### ISSUE THREAD

**Issue by rtwell** [uswds/uswds-for-designers#26]
I found a few errors we should clean up in the Illustrator file. I have marked them up in the attached PDF!
[Typography_v.8_RT.pdf](https://github.com/18F/web-design-standards-assets/files/278367/Typography_v.8_RT.pdf)

**Comment by rtwell** [comment]
to illustrate the spacing suggestion, indicated in purple:
![wds-spacing](https://cloud.githubusercontent.com/assets/12564977/15516584/074106da-21b9-11e6-98ce-d9403181140c.png)

**Comment by ericadeahl** [comment]
Addressed by #31
