### ISSUE TITLE
Update read me with instructions for using the color palettes

### ISSUE THREAD

**Issue by ericadeahl** [uswds/uswds-for-designers#30]
Add instructions for how to install the .ase to Illustrator and .sketchpalette to Sketch. This could either go in the existing readme or a separate .md in the colors folder.

**Comment by ericadeahl** [comment]
@kategarklavs Want to take a look at where these instructions should go? Instructions are essentially:

Sketch
- Add the Sketch palette plugin: https://github.com/andrewfiorillo/sketch-palettes
- From the color picker, select "Load Palette..." from either the Global Colors or Document Colors menu (Note: this will replace whatever colors are currently in the selected section)
- Navigate to WDS.sketchpalette

Illustrator
- Open the swatches palette
- In the swatches menu, select "open swatch library" then "other library"
- Navigate to web-design-standards-colors.ase

**Comment by kategarklavs** [comment]
@ericadeahl Will do! Am in my CFPB retro now, but I shall take a look this afternoon 👍

**Comment by kategarklavs** [comment]
@ericadeahl Just created a PR -- let me know what you think! (Happy to move the instructions if you'd rather have them in the colors folder.)

**Comment by ericadeahl** [comment]
Addressed by #34 🎉
