### ISSUE TITLE
Styles should be applied across components sticker sheet

### ISSUE THREAD

**Issue by mebates** [uswds/uswds-for-designers#35]
Each piece of type on the .ai component sticker sheet should have a paragraph and (optionally) a character style applied to it. This would ensure that all components match the standard. For example, is it noted somewhere in the standards that table text should be 16 px instead of 17 px, or is that a mistake on the component sticker sheet? In our application, we are keeping it 17 px so it's the standard body copy paragraph style.

**Comment by bradnunnally** [comment]
Corrected the table font size. Going to create a pull request to get this and #31 resolved.

/cc @juliaelman @shawnbot @yowill

**Comment by juliasolorzano** [comment]
Going to re-open. Talked with @bradnunnally and I think we were confused on the best path forward. Working on that now!

**Comment by juliasolorzano** [comment]
Okay! We are now done 🚀  merged in.
