### ISSUE TITLE
Design downloads on WDS site are not current

### ISSUE THREAD

**Issue by ericadeahl** [uswds/uswds-for-designers#37]
Pinging @yozlet @rogeruiz @donjo 

The design files (all the documents in the Components folder) in this repo are the most current version. However when you download the design files on [standards.gsa.gov/download](https://standards.usa.gov/download/), you get an older version of the files. The older versions of the files have "v.8" in the file name. The newer versions do not have a version number.

The Colors files are also not current. The Sketch download should pull in the file WDS.sketchpalette in the Colors folder. The Illustrator and EPS downloads should pull in the file web-design-standards-colors.ase in the Colors folder (but not the file web-design-standards-colors.ai).

Could someone please take a look and make sure the .zip compiler is pulling in the correct files? And can you confirm that this process should be automatic as we continue to make updates to the files?

**Comment by juliasolorzano** [comment]
@ericadeahl I've opened a PR to resolve the issue as well as added a note on how to avoid this happening in the future.

**Comment by juliasolorzano** [comment]
Fixed here: https://github.com/18F/web-design-standards/pull/1422
