### ISSUE TITLE
Add header component to sketch and ai sticker sheets

### ISSUE THREAD

**Issue by mebates** [uswds/uswds-for-designers#39]
I don't see the new header options in design assets. Am I missing something? Thanks! 

https://standards.usa.gov/headers/

**Comment by bradnunnally** [comment]
Updated sticker sheets which include the new headers is located in this pull request - https://github.com/18F/web-design-standards-assets/tree/update-sticker-sheet

This PR won't be ready until #35 is completed.

**Comment by mebates** [comment]
👏  👏  👏  👏  👏  
❤️  you all, keep it up
