### ISSUE TITLE
Include note about how Illustrator points convert to CSS pixels

### ISSUE THREAD

**Issue by Scotchester** [uswds/uswds-for-designers#4]
Illustrator points (i.e., font size/leading/stroke values) are equivalent to CSS pixels when the document's "Units" setting is set to pixels.

It's important to note this, because CSS points != to CSS pixels, and therefore are also != to Illustrator points.

Perhaps something can be noted in the README about this? It should probably also be noted in the guide itself, probably in the typography section.

**Comment by mollieru** [comment]
Hey @scotchester just noticed we didn't get back to you on this. Still feel like we should specify this in our docs?

Cc @carodew @angelk

**Comment by Scotchester** [comment]
I'm about to get on the plane to CFA Summit, but I'll check out what's been
released so far and follow up with you soon. Thanks!

**Comment by angelk** [comment]
@mollieru  let me be the cc-auto-forwarder
Cc @angel
