### ISSUE TITLE
Missing: 'View our list on GItHub' under 'Standards in the wild' on /whats-new/

### ISSUE THREAD

**Issue by NadyaNayme** [uswds/uswds-for-designers#45]
**Prroblem:** 
The following link is a 404.
https://github.com/18F/web-design-standards/blob/staging/WHO_IS_USING_USWDS.md

**On page:**
https://standards.usa.gov/whats-new/

**Expectation:**
I'm taken to a list of sites using the US Web Design Standards.

Upon investigation, the problem is that the link is to /staging/ instead of /develop/

**The proper link would be:**
https://github.com/18F/web-design-standards/blob/develop/WHO_IS_USING_USWDS.md

**Comment by juliasolorzano** [comment]
@Kyokou thank you for opening this issue! We've opened a pull request to update our documentation.

**Comment by juliasolorzano** [comment]
Pull request merged ^5. Closing this issue.
