### ISSUE TITLE
Modular symbols for Sketch library?

### ISSUE THREAD

**Issue by pglevy** [uswds/uswds-for-designers#51]
Hi there,

More of a question than an issue... 

I'm not sure what you're roadmap plans are, but I was starting to build out some reusable symbols with the goal of making mocking screens up in Sketch quicker and easier using the Library feature.

You might also break these components out into separate files to make contributing and updating less cumbersome.

Check out the symbols in this file, and let me know if you think any of this would be useful.
https://sketch.cloud/s/elwpj

**Comment by maya** [comment]
Hi @pglevy, thanks for reaching out! Sketch symbols sound like a useful thing to provide, but we do not have the bandwidth to implement anytime soon. Keep us posted on how it goes!

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
