### ISSUE TITLE
Unable to see components with Sketch in dark mode

### ISSUE THREAD

**Issue by maya** [uswds/uswds-for-designers#58]
I can't see everything in the Sketch file b/c there's no white background and my computer uses a dark mode. Adding a white artboard behind should alleviate this issue.

<img width="762" alt="Screen Shot 2019-10-08 at 5 08 55 PM" src="https://user-images.githubusercontent.com/5249443/66442154-740ce080-e9ee-11e9-8cf2-f11d5b9b43c9.png">

**Comment by maya** [comment]
Looks like I can toggle Sketch to use light mode instead of system defaults, so it should be OK in the meantime.

**Comment by sawyerh** [comment]
Screenshot of where you want to change this in your Sketch preferences: 

![image](https://user-images.githubusercontent.com/371943/73487624-57b5fa80-4375-11ea-8c52-f801f5bcabb6.png)

**Comment by thisisdano** [comment]
Fixed in assets v2.0
