### ISSUE TITLE
project-color-theme-primary.sketch references a missing font

### ISSUE THREAD

**Issue by pglevy** [uswds/uswds-for-designers#59]
### Description
Some text in the file references the font UnitedSans-Bold, which is not part of uswds-for-designers package.

### Ask
Update the file to use Public Sans as the other library files do.

### Steps
- [ ] Update the text "primary" in source file to use Public Sans.

![image](https://user-images.githubusercontent.com/5177337/67642450-4aa2ee80-f8e2-11e9-9805-6b843a1a02ff.png)

**Comment by thisisdano** [comment]
Fixed in assets v2.0
