### ISSUE TITLE
Agencies need Figma library!

### ISSUE THREAD

**Issue by sly-tanenbaum** [uswds/uswds-for-designers#88]
Howdy good USWDS folks! 

Is there a Figma library planned for the near future?

I am at HHS and would love to use USWDS in my projects; however, not having an official library kinda kills that initiative.

Thanks!

Cheers,
Sly

**Comment by mejiaj** [comment]
Hello @sly-tanenbaum, yes that's planned. 

It was confirmed on the August 2024. You can see the Q&A discussion in [USWDS Discussions](https://github.com/uswds/uswds/discussions/6060#discussioncomment-10630230).

**Comment by thisisdano** [comment]
This now exists! It's in Beta, but should be usable, and will be improved and maintained moving forward.
https://www.figma.com/community/file/1440921849343185329/uswds-design-kit-beta
